# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# 3 ways to switch directories to clear error
# - script: 
#     cd BananaStore
#     dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'

# - script: dotnet build BananaStore --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: BananaStore

# - script: dotnet test
#   displayName: dotnet test
#   workingDirectory: BananaStore

#TAks can encapuslate some userful logic so we don't have to write it all out in script step in this case
#the taks is both running test and publishing results to build itself
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './BananaStore/BananaStore.Tests'
    arguments: '-c $(buildConfiguration)'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(f17cbbb9-fdac-47fd-bde9-4c8aa1e23270)'
    appType: 'webApp'
    WebAppName: 'BananaStore20191023105024'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'